version: "2"

volumes:
  orderer.example.com:
  peer0.dimitra.example.com:
  peer1.dimitra.example.com:
  peer0.portesa.example.com:
  peer1.portesa.example.com:
  peer0.stelviotech.example.com:
  peer1.stelviotech.example.com:
networks:
  test:

services:
  orderer.example.com:
    extends:
      file: docker-compose-base.yaml
      service: orderer.example.com
    container_name: orderer.example.com
    networks:
      - test

  peer0.dimitra.example.com:
    extends:
      file: docker-compose-base.yaml
      service: peer0.dimitra.example.com
    container_name: peer0.dimitra.example.com
    networks:
      - test

  peer1.dimitra.example.com:
    extends:
      file: docker-compose-base.yaml
      service: peer1.dimitra.example.com
    container_name: peer1.dimitra.example.com
    networks:
      - test
  
  peer0.portesa.example.com:
    extends:
      file: docker-compose-base.yaml
      service: peer0.portesa.example.com
    container_name: peer0.portesa.example.com
    networks:
      - test

  peer1.portesa.example.com:
    extends:
      file: docker-compose-base.yaml
      service: peer1.portesa.example.com
    container_name: peer1.portesa.example.com
    networks:
      - test

  peer0.stelviotech.example.com:
    extends:
      file: docker-compose-base.yaml
      service: peer0.stelviotech.example.com
    container_name: peer0.stelviotech.example.com
    networks:
      - test

  peer1.stelviotech.example.com:
    extends:
      file: docker-compose-base.yaml
      service: peer1.stelviotech.example.com
    container_name: peer1.stelviotech.example.com
    networks:
      - test
 
  cli:
    container_name: cli
    image: hyperledger/fabric-tools:$IMAGE_TAG
    tty: true
    stdin_open: true
    environment:
      - SYS_CHANNEL=$SYS_CHANNEL
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.dimitra.example.com:7051
      - CORE_PEER_LOCALMSPID=DimitraMSP
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/dimitra.example.com/peers/peer0.dimitra.example.com/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/dimitra.example.com/peers/peer0.dimitra.example.com/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/dimitra.example.com/peers/peer0.dimitra.example.com/tls/ca.crt
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
      - /var/run/:/host/var/run/
      - ./scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
      - ./../chaincode/:/opt/gopath/src/github.com/hyperledger/fabric/peer/chaincode/
      - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
      - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
    depends_on:
      - orderer.example.com
      - peer0.dimitra.example.com
      - peer0.portesa.example.com
      - peer0.stelviotech.example.com
    
    networks:
      - test