Organizations:

- &OrdererOrg
    Name: Orderer
    ID: OrdererMSP
    MSPDir: crypto-config/ordererOrganizations/example.com/msp
    Policies:
        Readers:
            Type: Signature
            Rule: "OR('OrdererMSP.member')"
        Writers:
            Type: Signature
            Rule: "OR('OrdererMSP.member')"
        Admins:
            Type: Signature
            Rule: "OR('OrdererMSP.admin')"

- &Dimitra
    Name: DimitraMSP
    ID: DimitraMSP
    MSPDir: crypto-config/peerOrganizations/dimitra.example.com/msp
    Policies:
        Readers:
            Type: Signature
            Rule: "OR('DimitraMSP.admin', 'DimitraMSP.peer', 'DimitraMSP.client')"
        Writers:
            Type: Signature
            Rule: "OR('DimitraMSP.admin', 'DimitraMSP.client')"
        Admins:
            Type: Signature
            Rule: "OR('DimitraMSP.admin')"
    AnchorPeers:
        - Host: peer0.dimitra.example.com
          Port: 7051

- &Portesa
    Name: PortesaMSP
    ID: PortesaMSP
    MSPDir: crypto-config/peerOrganizations/portesa.example.com/msp
    Policies:
        Readers:
            Type: Signature
            Rule: "OR('PortesaMSP.admin', 'PortesaMSP.peer', 'PortesaMSP.client')"
        Writers:
            Type: Signature
            Rule: "OR('PortesaMSP.admin', 'PortesaMSP.client')"
        Admins:
            Type: Signature
            Rule: "OR('PortesaMSP.admin')"
    AnchorPeers:
        - Host: peer0.portesa.example.com
          Port: 7051

- &Stelviotech
    Name: StelviotechMSP
    ID: StelviotechMSP
    MSPDir: crypto-config/peerOrganizations/stelviotech.example.com/msp
    Policies:
        Readers:
            Type: Signature
            Rule: "OR('StelviotechMSP.admin', 'StelviotechMSP.peer', 'StelviotechMSP.client')"
        Writers:
            Type: Signature
            Rule: "OR('StelviotechMSP.admin', 'StelviotechMSP.client')"
        Admins:
            Type: Signature
            Rule: "OR('StelviotechMSP.admin')"
    AnchorPeers:
        - Host: peer0.stelviotech.example.com
          Port: 7051

Capabilities:
    Channel: &ChannelCapabilities
        V1_4_3: true
    Orderer: &OrdererCapabilities
        V1_4: true
    Application: &ApplicationCapabilities
        V1_4_2: true


Application: &ApplicationDefaults
    Organizations:

    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"
    Capabilities:
        <<: *ApplicationCapabilities


Orderer: &OrdererDefaults

    OrdererType: solo

    Addresses:
        - orderer.example.com:7050

    BatchTimeout: 2s
    BatchSize:
        MaxMessageCount: 10
        AbsoluteMaxBytes: 99 MB
        PreferredMaxBytes: 512 KB

    #No queda claro que hace esto ni si es necesario (creo que no)
    Kafka:
        Brokers:
            - 127.0.0.1:9092
    EtcdRaft:
        Consenters:
            - Host: orderer.example.com
              Port: 7050
              ClientTLSCert: crypto-config/ordererOrganizations/example.com/orderers/orderer.example.com/tls/server.crt
              ServerTLSCert: crypto-config/ordererOrganizations/example.com/orderers/orderer.example.com/tls/server.crt


    Organizations:

    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"


Channel: &ChannelDefaults
    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"
    Capabilities:
        <<: *ChannelCapabilities


Profiles:

    OrdererGenesis:
        <<: *ChannelDefaults
        Orderer:
            <<: *OrdererDefaults
            Organizations:
                - *OrdererOrg
            Capabilities:
                <<: *OrdererCapabilities
        Consortiums:
            SampleConsortium:
                Organizations:
                    - *Dimitra
                    - *Portesa
                    - *Stelviotech

    OrgChannel:
        Consortium: SampleConsortium
        Application:
            <<: *ApplicationDefaults
            Organizations:
                - *Dimitra
                - *Portesa
                - *Stelviotech
            Capabilities:
                <<: *ApplicationCapabilities