OrdererOrgs:
  - Name: Orderer
    Domain: example.com
    EnableNodeOUs: true
    Specs:
      - Hostname: orderer
      - Hostname: orderer2
      #CommonName en vez de Hostname sobreescribe el dominio

PeerOrgs:
  - Name: Dimitra
    Domain: dimitra.example.com
    EnableNodeOUs: true
    Template:
      Count: 2 #Number of peers
    Users:
      Count: 1 #Number of users
    
  - Name: Portesa
    Domain: portesa.example.com
    EnableNodeOUs: true
    Template:
      Count: 2 #Number of peers
    Users:
      Count: 1 #Number of users
  
  - Name: Stelviotech
    Domain: stelviotech.example.com
    EnableNodeOUs: true
    Template:
      Count: 2 #Number of peers
    Users:
      Count: 1 #Number of users